# Generated by Django 3.0.7 on 2020-07-10 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0005_auto_20200710_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
    ]
