# Generated by Django 3.0.7 on 2020-07-10 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0006_remove_userprofile_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='currency',
        ),
    ]
