# Generated by Django 3.0.7 on 2020-07-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylang',
            name='lang',
            field=models.CharField(choices=[], default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productlang',
            name='lang',
            field=models.CharField(choices=[], default=0, max_length=6),
            preserve_default=False,
        ),
    ]
