# Generated by Django 3.0.7 on 2020-07-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0002_auto_20200709_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category/images/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product/images/'),
        ),
    ]
