# Generated by Django 3.0.7 on 2020-07-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0003_auto_20200709_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Brand',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('Price', 'Price'), ('Brand', 'Brand'), ('Size', 'Size'), ('Color', 'Color'), ('Size-Color', 'Size-Color')], default='color', max_length=10),
        ),
    ]
