# Generated by Django 3.0.7 on 2020-07-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0004_auto_20200709_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylang',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('fr', 'French'), ('ar', 'Arabic')], max_length=6),
        ),
        migrations.AlterField(
            model_name='productlang',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('fr', 'French'), ('ar', 'Arabic')], max_length=6),
        ),
    ]
