# Generated by Django 3.0.7 on 2020-07-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0006_product_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylang',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('fr', 'French'), ('ar', 'Arabic'), ('sw', 'Swahili')], max_length=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('Price', 'Price'), ('Brand', 'Brand'), ('Size', 'Size'), ('Color', 'Color'), ('Size-Color', 'Size-Color')], default='Color', max_length=10),
        ),
        migrations.AlterField(
            model_name='productlang',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('fr', 'French'), ('ar', 'Arabic'), ('sw', 'Swahili')], max_length=6),
        ),
    ]
