# Generated by Django 3.0.7 on 2020-07-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0007_auto_20200710_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
