# Generated by Django 3.0.7 on 2020-07-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0009_auto_20200716_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variants',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('None', 'None'), ('Brand', 'Brand'), ('Size', 'Size'), ('Color', 'Color'), ('Size-Color', 'Size-Color')], default='None', max_length=10),
        ),
    ]
