# Generated by Django 3.0.7 on 2020-07-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0010_auto_20200716_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Refurblished', 'Refurblished'), ('Used', 'Used')], default='New', max_length=30),
        ),
        migrations.AddField(
            model_name='variants',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Refurblished', 'Refurblished'), ('Used', 'Used')], default='New', max_length=30),
        ),
    ]
