# Generated by Django 3.0.7 on 2020-07-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0012_auto_20200716_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icons',
            field=models.ImageField(default=0, upload_to='icons/'),
            preserve_default=False,
        ),
    ]
