# Generated by Django 3.0.7 on 2020-07-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0013_category_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylang',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'عربى'), ('sw', 'Swahili'), ('hi', 'हिन्दी')], max_length=6),
        ),
        migrations.AlterField(
            model_name='productlang',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'عربى'), ('sw', 'Swahili'), ('hi', 'हिन्दी')], max_length=6),
        ),
    ]
