# Generated by Django 3.0.7 on 2020-07-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0002_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='lang',
            field=models.CharField(blank=True, choices=[], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='settinglang',
            name='lang',
            field=models.CharField(choices=[], default=0, max_length=6),
            preserve_default=False,
        ),
    ]
