# Generated by Django 3.0.7 on 2020-07-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0004_auto_20200710_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverts',
            name='image',
            field=models.ImageField(blank=True, upload_to='adverts/images/'),
        ),
    ]
