# Generated by Django 3.0.7 on 2020-07-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0006_auto_20200710_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('tr', 'Turkish'), ('ar', 'Arabic'), ('sw', 'Swahili'), ('kik', 'Kimîîru')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='settinglang',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('ar', 'Arabic'), ('sw', 'Swahili'), ('kik', 'Kimîîru')], max_length=6),
        ),
    ]
