# Generated by Django 3.0.7 on 2020-07-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0007_auto_20200716_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ar', 'عربى'), ('sw', 'Swahili'), ('hi', 'हिन्दी')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='settinglang',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'عربى'), ('sw', 'Swahili'), ('hi', 'हिन्दी')], max_length=6),
        ),
    ]
